### ISSUE TITLE
Error when trying to find carriageway and position from point coordinates

### ISSUE THREAD

**Issue by Winda2** [johnbullnz/pyramm#31] opened 2023-02-06 21:41 UTC
Used the pyramm example to retrieve the position:
```
centreline = conn.centreline()
point = Point((172.618567, -43.441594))  # Shapely Point object
position = centreline.position(point, point_crs=4326)
```

This resulted in this error:

```
    raise NotImplementedError(
NotImplementedError: Multi-part geometries do not provide a coordinate sequence
```

Attributed to the conn.centreline()

**Comment by johnbullnz** [comment] 2023-05-11 02:19
@Winda2 please try the latest version of *pyramm* (v1.22) and see if you still have this issue.

**Comment by johnbullnz** [comment] 2023-11-19 23:43
Closing as unable to reproduce. Please open a new issue if the problem persists.

**Closed as completed by johnbullnz** 2023-11-19 23:43 UTC
